### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by abtris**
Fixed dependencies for #92

### CODE REVIEW

**Comment by abtris** [comment]
@kylef I make some fixes of dependencies for `apiary-client`

**Comment by freaz** [comment]
@abtris :+1:

**Comment by honzajavorek** [comment]
Does this close https://github.com/apiaryio/apiary-client/issues/91 and https://github.com/apiaryio/apiary-client/issues/92, too?

**Comment by freaz** [comment]
@hj no, this fixes only development dependencies

**Pull request merged**
