### PR TITLE
Fixes issue where message was not be passed on publish

### PR DESCRIPTION
**Pull request by smizell**
This does not change the API, but is merely a fix where we pass the correct option through the HTTP POST.

I was testing this and figured I’d just fix while I was looking at it :)

cc @abtris

### CODE REVIEW

**Comment by steve43** [comment]
Note that the `publish` command uses `message` instead of `commit_message`. This was the issue, as the `Publish` class was wanting `commit_message`.

**Comment by smizell** [comment]
Note that the publish command uses message instead of commit_message. This was the issue, as the Publish class was wanting commit_message.

**Comment by abtris** [comment]
Try remove from Rakefile - `t.rspec_opts = "-fd"`

**Comment by abtris** [comment]
Released as 0.3.4

**Pull request merged**
