### PR TITLE
Make README.md help output match cli.rb

### PR DESCRIPTION
**Pull request by jrep**
There are several issues with the help. This PR only addresses one: get all the capabilities of `cli.rb` documented somewhere.

### CODE REVIEW

**Comment by jrep** [comment]
I don't think the circleci check failure is my fault. I can't verify this locally, because:

```
> apiary fetch --api-name apiaryclienttest
Apiary service responded with an error: 403 Forbidden
```

**Comment by honzajavorek** [comment]
Hi Jack, thanks!

There are some related issues about README:

- `apiary help` doesn't contain all capabilities of Apiary client - https://github.com/apiaryio/apiary-client/issues/78
- My take on updating the README - https://github.com/apiaryio/apiary-client/pull/87 (blocked by #78)

Your changes address just formatting, which is fine and which I think can be merged regardless the issues above.

--------

Your changes should not affect the CircleCI build indeed. It seems like it got somehow broken by recent changes. Let us look at it and thanks for pointing it out!

**Comment by jrep** [comment]
@honzajavorek By my reading, your #87 completely eliminates the command-line options documentation, both in-line and by reference to http://client.apiary.io. This seems like the wrong move to me. I get the feeling your focus in #87 is primarily API use and developing, rather than CLI use; why don't we cooperate to enhance all uses?

My change includes more than formatting, it adds documentation for several options supported (even *required*!) by the tool and Thor, but not documented here. Prompted by your removals, I looked again at the [full documentation](http://client.apiary.io), which is much better than it was the last time I reviewed it. 

How about if I rewrite my PR like this:

1. Include true output from `apiary --help`, as a minimal aid to the CLI user.
1. Include the `apiary --help subcommand` hint, lifted from client.apiary.io, as a clue to advanced dox.
1. Include the link to the [full documentation](http://client.apiary.io).
1. Review client.apiary.io for completeness; deal with any deficits over there, not here.

**Comment by honzajavorek** [comment]
@jrep 

One of aims of #87 was to DRY out the CLI docs. It removes the docs in written form and points user to the `apiary help` command, which should provide all the docs itself. That is not the case in this moment though, that's why #87 is blocked by #78, which is about updating the CLI help information so it contains full documentation.

I see pointing user to `apiary help` may not be sufficient and the CLI docs are really needed in the README. But then let's prevent the README to go stale. Let's at least add a check in CI, which takes output of `apiary help` and if README's CLI options block doesn't equal to it, it will fail.

If you are willing to contribute this much, it would be awesome if you could take the three issues/PRs (#78, #87, #94) and address them together. My take would be:

- Make sure CLI implementation using Thor is up to date and with as much built-in docs as possible, with all missing things being present, thus being part of output of `apiary help`.
- Take output of the CLI's help and paste it into the README of #87 as a new section, similar to something we have in place in current README.
- Merge #87 with #94 so it contains good ideas and updates from both.

Eventually:

- Review client.apiary.io for completeness; deal with any deficits over there, not here.
- Set up a CI check so README can't get out of sync. (I'm eager to do this.)

What do you think about this?

**Comment by jrep** [comment]
> On Aug 24, 2015, at 1:01 AM, Honza Javorek <notifications@github.com> wrote:
> 
> If you are willing to contribute this much, it would be awesome if you could take the three issues/PRs (#78 <https://github.com/apiaryio/apiary-client/issues/78>, #87 <https://github.com/apiaryio/apiary-client/pull/87>, #94 <https://github.com/apiaryio/apiary-client/pull/94>) and address them together. My take would be:
> 
> Make sure CLI implementation using Thor is up to date and with as much built-in docs as possible, with all missing things being present, thus being part of output of apiary help.
> Take output of the CLI's help and paste it into the README of #87 <https://github.com/apiaryio/apiary-client/pull/87> as a new section, similar to something we have in place in current README.
> Merge #87 <https://github.com/apiaryio/apiary-client/pull/87> with #94 <https://github.com/apiaryio/apiary-client/pull/94> so it contains good ideas and updates from both.

I'm willing. But a problem here is that, so far as I can tell, Thor is simply incapable of rendering full documentation in a single command. The command apiary help (which is handled by Thor) only has the ability to display the subcommands ('fetch', 'preview', ...) and their required method_options  (if any). The optional method_options can only be displayed with apiary help COMMAND. For example:

> apiary help
Commands:
  apiary fetch --api-name=API_NAME    # Fetch apiary.apib from API_NAME.apiary.io
  apiary help [COMMAND]               # Describe available commands or one specific...
  apiary preview                      # Show API documentation in default browser
  apiary publish --api-name=API_NAME  # Publish apiary.apib on docs.API_NAME.apiary.io
  apiary version                      # Show version


> apiary help fetch
Usage:
  apiary fetch --api-name=API_NAME

Options:
  --api-name=API_NAME
  [--api-host=HOST]    # Specify apiary host
  [--output=FILE]      # Write apiary.apib into specified file

Fetch apiary.apib from API_NAME.apiary.io

So I'm not clear on how much should be in README.md. What I tried to do was to reduce the ~50 lines of "for all COMMANDS: apiary help COMMAND" into something more readable -- but this is likely not machine-auditable.



--
Jack Repenning
Jack@netgate.net

**Comment by honzajavorek** [comment]
> Thor is simply incapable of rendering full documentation in a single command.

Ah! I did not know that.

Then let's keep the "README vs. CLI" check just as an idea for now and let's at least fix the inconsistency, DRY or not. I agree we should have full written docs in README then, together with as-full-as-possible docs right in the CLI.

**Comment by jrep** [comment]
I'm going to close this PR. I'm working on a new PR that combines #78, #87, and #94. The curious can monitor my progress at [my fork](https://github.com/jrep/apiary-client).

**Comment by jrep** [comment]
I have made #96, which I believe encompasses and obsoletes this PR.

**Pull request closed without merging**
