### PR TITLE
Preview command uses OS' native files opener

### LINKED ISSUE #101: "open" command does not exist in Linux.
The client should check if its running on a Linux system, and maybe use xdg-open instead?

### PR DESCRIPTION
**Pull request by tsusanka**
Uses https://github.com/rdp/os 
Closes #101

[Review on Reviewable](https://reviewable.io/reviews/apiaryio/apiary-client/105)

### CODE REVIEW

**Comment by jrep** [comment]
Perhaps also this?

```
diff --git a/lib/apiary/command/preview.rb b/lib/apiary/command/preview.rb
index 276ac23..12ad82f 100644
--- a/lib/apiary/command/preview.rb
+++ b/lib/apiary/command/preview.rb
@@ -132,7 +132,7 @@ module Apiary
       private
 
       def browser_options
-        "-a #{BROWSERS[@options.browser.to_sym]}" if @options.browser
+        "-a #{BROWSERS[@options.browser.to_sym]}" if @options.browser && OS.x?
       end
     end
   end
```

The "-a browsername" for is definitely OSX-specific.

`xdg-open` (Linux) doesn't seem to provide anything meaningful for browser_options.

I don't know about `start` (Windows).

**Comment by tsusanka** [comment]
I am not sure it's needed. The function `open_generated_page` results to `xdg-open /tmp/apiary-preview.html` on my Linux and works properly. I guess it depends on the options settings. Maybe someone could give it a try on windows?

**Comment by jrep** [comment]
But if you use "--browser" on Linux, xdg-open is unhappy:

```
> bin/apiary preview --browser=chrome --path=$HOME/identityservicesapis.apib 
xdg-open: unexpected option '-a'
Try 'xdg-open --help' for more information.
```

**Comment by abtris** [comment]
Maybe use [launchy gem](https://github.com/copiousfreetime/launchy) can be better. This gem is used in  `heroku open` command.

**Comment by abtris** [comment]
I think exception for browser in OSX is good way.

**Comment by tsusanka** [comment]
> But if you use "--browser" on Linux, xdg-open is unhappy:

Oh, sorry, I get it now. I've added your changes.

I am not sure how I should fix the test. I may delete the option in README, but that's not very nice and it will fail on mac. Any ideas?

**Comment by jrep** [comment]
README is hard, yes. FWIW, I'd rather annotate the options in README "OS X Only", suppress both behavior and --help output, and delete the test (as being no longer portable), than delete the behavior just to make a test case we know how to write :(

**Comment by MaxPleaner** [comment]
Why is the `open` or `xdg-open` command necessary? Can't the CLI just output a link to a local index file, and trust the developer to copy and paste that into their browser? Might be labor-intensive but at least it would work on Linux.

**Comment by jrep** [comment]
@MaxPleaner : does `xdg-open` ***not*** work for you on Linux? It does for me ... but there are so many Linuces ...

**Comment by MaxPleaner** [comment]
@jrep yeah it is installed, which i didnt realize when i wrote the first comment. still, the reason i'm commenting on this issue is because i had the same issue.

**Comment by jrep** [comment]
Well, the original impetus was to make the docs match the behavior. Chopping a feature out just because it's hard to document seems a bit regressive ;-).

Speaking as one who uses the tool, uses the docs, has been inconvenienced by the mismatch, and is willing to put in the labor to fix it all, I'm willing to give it more thought before abandoning the effort entirely.

I am, however, tempted to take a low-ball approach, such as merely annotating certain lines with platform-support indications like "OS X and Linux only".

**Pull request closed without merging**
